export const charactersConstants = {
    START_DOWNLOAD_CHARACTERS : 'START_DOWNLOAD_CHARACTERS',
    SUCCESS_DOWNLOAD_CHARACTERS : 'SUCCESS_DOWNLOAD_CHARACTERS',
    ERROR_DOWNLOAD_CHARACTERS : 'ERROR_DOWNLOAD_CHARACTERS',
    GET_ALL_CHARACTERS: "GET_ALL_CHARACTERS",
}